# Generated by Django 5.0.1 on 2025-04-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
